### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by xqggw** [OsLeon/fish_recognition#1]
export CPU_NUM=16 # for example, set CPU_NUM as number of physical CPU core which is 16.

!!! The default number of CPU_NUM=1.
2022-05-18 23:05:14 [INFO]      Model[ResNet50_vd_ssld] loaded.
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\flask\app.py", line 2095, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Program Files\Python37\lib\site-packages\flask\app.py", line 2080, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Program Files\Python37\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Program Files\Python37\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Program Files\Python37\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files\Python37\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\biyesheji_xiangmu\fish_recognition-master\fish_backbone\app.py", line 57, in upload_file
    yucejieguo = str(core.main.prediction(image_path))
  File "D:\biyesheji_xiangmu\fish_recognition-master\fish_backbone\core\main.py", line 9, in prediction
    result = model.predict(test_jpg)
  File "C:\Program Files\Python37\lib\site-packages\paddlex\cv\models\classifier.py", line 355, in predict
    input_channel=input_channel)
  File "C:\Program Files\Python37\lib\site-packages\paddlex\cv\models\classifier.py", line 309, in _preprocess
    batch_data.append(transforms(image))
  File "C:\Program Files\Python37\lib\site-packages\paddlex\cv\transforms\cls_transforms.py", line 90, in __call__
    self.data_type = im.dtype
AttributeError: 'NoneType' object has no attribute 'dtype'

what happened？

**Comment by stoneloong** [comment]
Hi，It may be the problem of numpy version. My working environment numpy version number is 1.19.5.
